// Crystal FMBE's directory compiler (a DIRECTORY_DSLS entry): every *.fmbe file under a mod's `content.fmbeDsl`
// directory is parsed and compiled; the result ships as
//   - `.openrock-virtual/openrock-fmbe-data.js` - a generated ES module (`export const SCENES = {...}`) importable from
//     in-world scripts as `@openrock/virtual/openrock-fmbe-data`,
//   - `fmbe/<id>.json` - the same scenes as plain JSON, for tooling.
"use strict";

const fs = require("fs");
const path = require("path");
const { parse } = require("./parser.js");
const { compileProgram } = require("./compile.js");
const { signatureForFiles, withCompileCache } = require("../devCache.js");

const VIRTUAL_NAME = "openrock-fmbe-data";
const LIB_DIR = path.join(__dirname, "..", "..", "libs", "fmbe", "scripts", "fmbe");
const RUNTIME_FILES = [path.join(__dirname, "parser.js"), path.join(__dirname, "compile.js"), ...["spec.cjs", "commands.cjs", "ease.cjs", "items.cjs", "simulate.cjs", "wikiSystems.cjs"].map(f => path.join(LIB_DIR, f))];
const compileCache = new Map();

const emitDataModule = scenes => `// GENERATED by OpenRock Crystal FMBE - do not edit.\nexport const SCENES = ${JSON.stringify(Object.fromEntries(scenes.map(s => [s.id, s])), null, 1)};\n`;

function compileFmbeDsl(fmbeDir) {
    if (!fs.existsSync(fmbeDir)) return { bp: {}, rp: {} };
    const files = fs.readdirSync(fmbeDir).filter(f => f.endsWith(".fmbe")).sort();
    if (files.length === 0) return { bp: {}, rp: {} };
    const abs = files.map(f => path.join(fmbeDir, f));
    return withCompileCache(compileCache, fmbeDir, signatureForFiles([...abs, ...RUNTIME_FILES]), [__dirname], () => {
        const scenes = [];
        const seen = new Map();
        files.forEach((file, i) => {
            const source = fs.readFileSync(abs[i], "utf8");
            const { scenes: compiled, warnings } = compileProgram(parse(source, file), { source, filename: file });
            for (const w of warnings) console.warn(`  WARNING: ${w}`);
            for (const s of compiled) {
                if (seen.has(s.id)) throw new Error(`duplicate scene id "${s.id}" in ${file} (already defined in ${seen.get(s.id)})`);
                seen.set(s.id, file);
                scenes.push(s);
            }
        });
        const bp = { [`.openrock-virtual/${VIRTUAL_NAME}.js`]: emitDataModule(scenes) };
        for (const s of scenes) bp[`fmbe/${s.id}.json`] = s;
        return { bp, rp: {} };
    });
}

module.exports = { compileFmbeDsl, emitDataModule, VIRTUAL_NAME };
