// Crystal Cinema's directory compiler (the DIRECTORY_DSLS entry point):
// every *.cinema file under a mod's `content.cinemaDsl` directory is parsed
// and compiled; the result ships as
//   - `.openrock-virtual/openrock-cinema-data.js` - a generated ES module
//     (`export const CUTSCENES = {...}`) importable from in-world scripts as
//     `@openrock/virtual/openrock-cinema-data` (see src/virtualModules.js),
//   - `cinema/<id>.json` - the same timelines as plain JSON, for tooling.
"use strict";

const fs = require("fs");
const path = require("path");
const { parse } = require("./parser.js");
const { compileProgram } = require("./timeline.js");
const { lintTimeline } = require("./lint.js");
const { signatureForFiles, withCompileCache } = require("../devCache.js");

const VIRTUAL_NAME = "openrock-cinema-data";
const RUNTIME_FILES = ["lexer.js", "parser.js", "timeline.js", "verbs.js"].map(f => path.join(__dirname, f)).concat(["lexer.js", "errors.js", "text.js"].map(f => path.join(__dirname, "..", "crystal", f)));
const compileCache = new Map();

function emitDataModule(timelines) {
    const byId = Object.fromEntries(timelines.map(t => [t.id, t]));
    return `// GENERATED by OpenRock Crystal Cinema - do not edit.\nexport const CUTSCENES = ${JSON.stringify(byId, null, 1)};\n`;
}

function compileCinemaDsl(cinemaDir, { vars = {} } = {}) {
    const ns = vars.ns || null;
    if (!fs.existsSync(cinemaDir)) return { bp: {}, rp: {} };
    const files = fs.readdirSync(cinemaDir).filter(f => f.endsWith(".cinema")).sort();
    if (files.length === 0) return { bp: {}, rp: {} };
    const abs = files.map(f => path.join(cinemaDir, f));
    const signature = `${signatureForFiles([...abs, ...RUNTIME_FILES])}|ns:${ns}`;
    return withCompileCache(compileCache, cinemaDir, signature, [__dirname], () => {
        const timelines = [];
        const seenIds = new Map();
        const lintIssues = [];
        const refs = [], defs = [];
        files.forEach((file, i) => {
            const source = fs.readFileSync(abs[i], "utf8");
            const program = parse(source, file, { ns });
            refs.push(...program.links);
            for (const w of program.warnings ?? []) console.warn(`  WARNING: ${file}:${w.line}:${w.col}: ${w.message}`);
            const compiled = compileProgram(program, { source, filename: file });
            for (const t of compiled) {
                if (seenIds.has(t.id)) throw new Error(`duplicate cutscene id "${t.id}" in ${file} (already defined in ${seenIds.get(t.id)})`);
                seenIds.set(t.id, file);
                timelines.push(t);
                if (ns) defs.push({ kind: "cutscene", id: `${ns}:${t.id}` });
                lintIssues.push(...lintTimeline(t).map(w => `${file}: ${w}`));
            }
        });
        if (lintIssues.length) {
            for (const issue of lintIssues) console.warn(`  WARNING: ${issue}`);
        }
        const bp = { [`.openrock-virtual/${VIRTUAL_NAME}.js`]: emitDataModule(timelines) };
        for (const t of timelines) bp[`cinema/${t.id}.json`] = t;
        return { bp, rp: {}, refs, defs };
    });
}

module.exports = { compileCinemaDsl, emitDataModule, VIRTUAL_NAME };
