// OpenRock pathfinding-demo - a real, in-game-testable proof of
// @openrock/pathfinding's slot-pool technique, used as a REAL import (not a
// hand-duplicated reimplementation) - the exact gap OR-Track N closed:
// libs/pathfinding/src/register.js's functions are hoisted to real
// top-level CommonJS exports, so esbuild's real CJS->ESM interop resolves
// `import { navigateToCoordinate } from "@openrock/pathfinding"` into the
// real, already-unit-tested library code, bundled straight into this file's
// compiled output (see openrock.mod.json's real dependsOn entry for
// "@openrock/pathfinding", and buildPipeline.js's provides.api-based alias
// resolution). The matching real entity JSON (bp/entities/nav_test.json,
// generated by tools/lib/genNavSlots.js) uses the SAME default tag prefixes
// (openrock_anchor_slot_N / openrock_navigating_slot_N) the library's own
// slotTag()/slotFilterTag() produce - no manual prefix coordination needed.
"use strict";

import { world, system } from "@minecraft/server";
import { createSlotPool, navigateToCoordinate } from "@openrock/pathfinding";

const NS = "prd"; // matches openrock.mod.json's "namespace" - can't use {{ns}} here, that substitution only applies to bp/rpOverlayDir JSON, not bundled scripts.
const SLOT_COUNT = 5; // matches genNavSlots(5) in tools/lib/genNavSlots.js's call that produced bp/entities/nav_test.json

const pool = createSlotPool(SLOT_COUNT);
const inUseByEntity = new Map(); // entity.id -> the real handle navigateToCoordinate() returned

// The real, dependency-injected side effects @openrock/pathfinding's
// navigateToCoordinate() needs - this is the one place actual @minecraft/server
// calls happen; the library itself stays fully unit-testable without them.
const hooks = {
    spawnAnchor(location, dimension) { return dimension.spawnEntity(`${NS}:nav_anchor`, location); },
    teleportAnchor(anchor, location) { anchor.teleport(location); },
    removeAnchor(anchor) { try { anchor.remove(); } catch { /* anchor may already be gone */ } },
    tagEntity(entity, tag) { entity.addTag(tag); },
    untagEntity(entity, tag) { entity.removeTag(tag); },
};

function startNavigation(entity, target, dimension) {
    const handle = navigateToCoordinate(pool, entity, target, dimension, hooks);
    if (!handle) {
        world.sendMessage(`[${NS}] no free navigation slots (pool of ${SLOT_COUNT} exhausted)`);
        return false;
    }
    inUseByEntity.set(entity.id, handle);
    return true;
}

function stopNavigation(entity) {
    const handle = inUseByEntity.get(entity.id);
    if (!handle) return false;
    handle.cancel();
    inUseByEntity.delete(entity.id);
    return true;
}

// --- scriptevent test harness: /scriptevent prd:navtest_spawn|navtest_goto|navtest_cancel|navtest_status ---
system.afterEvents.scriptEventReceive.subscribe(event => {
    if (!event.id.startsWith(`${NS}:`)) return;
    const player = event.sourceEntity;
    if (!player) return;
    const dimension = player.dimension;

    if (event.id === `${NS}:navtest_spawn`) {
        const spawnLoc = { x: player.location.x, y: player.location.y, z: player.location.z };
        const testEntity = dimension.spawnEntity(`${NS}:nav_test`, spawnLoc);
        player.sendMessage(`[${NS}] spawned nav_test ${testEntity.id} at your feet.`);
        return;
    }

    if (event.id === `${NS}:navtest_goto`) {
        const parts = (event.message ?? "").trim().split(/\s+/).map(Number);
        if (parts.length !== 3 || parts.some(Number.isNaN)) {
            player.sendMessage(`[${NS}] usage: /scriptevent ${NS}:navtest_goto <x> <y> <z>`);
            return;
        }
        const [x, y, z] = parts;
        const nearby = dimension.getEntities({ type: `${NS}:nav_test`, location: player.location, maxDistance: 64, closest: 1 });
        if (nearby.length === 0) {
            player.sendMessage(`[${NS}] no nav_test entity nearby - run ${NS}:navtest_spawn first.`);
            return;
        }
        const started = startNavigation(nearby[0], { x, y, z }, dimension);
        if (started) player.sendMessage(`[${NS}] navigating ${nearby[0].id} to (${x}, ${y}, ${z}) - watch it path there via real native pathfinding.`);
        return;
    }

    if (event.id === `${NS}:navtest_cancel`) {
        const nearby = dimension.getEntities({ type: `${NS}:nav_test`, location: player.location, maxDistance: 64, closest: 1 });
        if (nearby.length === 0) {
            player.sendMessage(`[${NS}] no nav_test entity nearby.`);
            return;
        }
        const cancelled = stopNavigation(nearby[0]);
        player.sendMessage(cancelled ? `[${NS}] navigation cancelled, slot released.` : `[${NS}] that entity wasn't navigating.`);
        return;
    }

    if (event.id === `${NS}:navtest_status`) {
        player.sendMessage(`[${NS}] free slots: ${pool.available()}/${SLOT_COUNT}, in-use: ${pool.inUseCount()}`);
    }
});

// World::sendMessage (and most world-interacting calls) can't run during
// "early execution" - the brief window while the script is first being
// evaluated, before the world is actually ready. Deferring via system.run()
// pushes this to the next real tick, after early execution ends. A real bug
// caught via the content log the first time this deployed: calling
// world.sendMessage() directly here crashed the WHOLE script on load
// (uncaught at module scope), meaning the scriptevent subscription above
// never even registered - nothing happened for any /scriptevent command.
system.run(() => {
    world.sendMessage(`[${NS}] pathfinding-demo loaded - try /scriptevent ${NS}:navtest_spawn`);
});
