// OpenRock pathfinding-demo - a real, minimal, in-game-testable proof of
// @openrock/pathfinding's slot-pool technique (libs/pathfinding/src/register.js)
// and the matching real entity JSON generated by tools/lib/genNavSlots.js
// (mods/pathfinding-demo/bp/entities/nav_test.json's 5 component groups).
//
// The slot-pool bookkeeping below is a small, direct reimplementation of
// @openrock/pathfinding's already-unit-tested logic, NOT an import of it -
// OpenRock's libs/* are plain CommonJS "register(kernel, ctx)" modules meant
// for the build-time Node kernel (see buildPipeline.js's own header comment
// on this being a real, still-open gap: those libraries have never been
// proven to run inside Minecraft's actual ES-module-only script engine).
// This demo deliberately sidesteps that unresolved question so THIS pass's
// real, testable goal - does the entity JSON slot-pool technique itself
// actually work in a real world - isn't blocked on a separate, harder
// problem. The bookkeeping here mirrors @openrock/pathfinding's real,
// tested shape closely enough that porting it to a real import later (once
// that ES-module question is resolved) should be close to a drop-in swap.
"use strict";

import { world, system } from "@minecraft/server";

const NS = "prd"; // matches openrock.mod.json's "namespace" - can't use {{ns}} here, that substitution only applies to bp/rpOverlayDir JSON, not bundled scripts.
const SLOT_COUNT = 5; // matches genNavSlots(5) in tools/lib/genNavSlots.js's call that produced bp/entities/nav_test.json

function slotTag(slot) { return `${NS}_anchor_slot_${slot}`; }
function slotFilterTag(slot) { return `${NS}_navigating_slot_${slot}`; }

// --- the slot pool (mirrors @openrock/pathfinding's real, tested API) ---
const freeSlots = [];
for (let i = SLOT_COUNT - 1; i >= 0; i--) freeSlots.push(i);
const inUseByEntity = new Map(); // entity.id -> { slot, anchor }

function acquireSlot() { return freeSlots.length > 0 ? freeSlots.pop() : null; }
function releaseSlot(slot) { freeSlots.push(slot); }

function navigateToCoordinate(entity, location, dimension) {
    const slot = acquireSlot();
    if (slot === null) {
        world.sendMessage(`[${NS}] no free navigation slots (pool of ${SLOT_COUNT} exhausted)`);
        return false;
    }
    const anchor = dimension.spawnEntity(`${NS}:nav_anchor`, location);
    anchor.addTag(slotTag(slot));
    entity.addTag(slotFilterTag(slot));
    inUseByEntity.set(entity.id, { slot, anchor });
    return true;
}

function cancelNavigation(entity) {
    const handle = inUseByEntity.get(entity.id);
    if (!handle) return false;
    entity.removeTag(slotFilterTag(handle.slot));
    try { handle.anchor.remove(); } catch { /* anchor may already be gone */ }
    releaseSlot(handle.slot);
    inUseByEntity.delete(entity.id);
    return true;
}

// --- scriptevent test harness: /scriptevent prd:navtest_spawn|navtest_goto|navtest_cancel ---
system.afterEvents.scriptEventReceive.subscribe(event => {
    if (!event.id.startsWith(`${NS}:`)) return;
    const player = event.sourceEntity;
    if (!player) return;
    const dimension = player.dimension;

    if (event.id === `${NS}:navtest_spawn`) {
        const spawnLoc = { x: player.location.x, y: player.location.y, z: player.location.z };
        const testEntity = dimension.spawnEntity(`${NS}:nav_test`, spawnLoc);
        player.sendMessage(`[${NS}] spawned nav_test ${testEntity.id} at your feet.`);
        return;
    }

    if (event.id === `${NS}:navtest_goto`) {
        const parts = (event.message ?? "").trim().split(/\s+/).map(Number);
        if (parts.length !== 3 || parts.some(Number.isNaN)) {
            player.sendMessage(`[${NS}] usage: /scriptevent ${NS}:navtest_goto <x> <y> <z>`);
            return;
        }
        const [x, y, z] = parts;
        const nearby = dimension.getEntities({ type: `${NS}:nav_test`, location: player.location, maxDistance: 64, closest: 1 });
        if (nearby.length === 0) {
            player.sendMessage(`[${NS}] no nav_test entity nearby - run ${NS}:navtest_spawn first.`);
            return;
        }
        const started = navigateToCoordinate(nearby[0], { x, y, z }, dimension);
        if (started) player.sendMessage(`[${NS}] navigating ${nearby[0].id} to (${x}, ${y}, ${z}) - watch it path there via real native pathfinding.`);
        return;
    }

    if (event.id === `${NS}:navtest_cancel`) {
        const nearby = dimension.getEntities({ type: `${NS}:nav_test`, location: player.location, maxDistance: 64, closest: 1 });
        if (nearby.length === 0) {
            player.sendMessage(`[${NS}] no nav_test entity nearby.`);
            return;
        }
        const cancelled = cancelNavigation(nearby[0]);
        player.sendMessage(cancelled ? `[${NS}] navigation cancelled, slot released.` : `[${NS}] that entity wasn't navigating.`);
        return;
    }

    if (event.id === `${NS}:navtest_status`) {
        player.sendMessage(`[${NS}] free slots: ${freeSlots.length}/${SLOT_COUNT}, in-use: ${inUseByEntity.size}`);
    }
});

world.sendMessage(`[${NS}] pathfinding-demo loaded - try /scriptevent ${NS}:navtest_spawn`);
