// Cross-package merging of localization output (several packages each contribute texts/*.lang,
// texts/languages.json and the runtime table) plus the pack.name / pack.description strings the
// generated pack manifests reference.
"use strict";

const { parseLang, serializeLang } = require("../libs/localization/src/langFile.js");
const { HEADER, RUNTIME_MODULE_PREFIX } = require("../libs/localization/src/emit.js");

const RUNTIME_KEY = ".openrock-virtual/localization-tables.js";
const asText = v => (Buffer.isBuffer(v) ? v.toString("utf8") : String(v));

const isLangFile = rel => /^texts\/[^/]+\.lang$/.test(rel);
const isMergedLangOutput = rel => isLangFile(rel) || rel === "texts/languages.json" || rel === RUNTIME_KEY;

function parseRuntime(text) {
    const body = text.slice(text.indexOf(RUNTIME_MODULE_PREFIX) + RUNTIME_MODULE_PREFIX.length).replace(/;\s*$/, "");
    return JSON.parse(body);
}

/** Merges `incoming` (later package wins) into what `existing` holds at `rel`; both are Buffer|string. Returns the merged string. */
function mergeLangOutput(rel, existing, incoming) {
    if (isLangFile(rel)) return serializeLang(new Map([...parseLang(asText(existing)), ...parseLang(asText(incoming))]), { header: HEADER });
    if (rel === "texts/languages.json") {
        const ids = [...new Set([...JSON.parse(asText(existing)), ...JSON.parse(asText(incoming))])];
        ids.sort((a, b) => (a === "en_US" ? -1 : b === "en_US" ? 1 : a.localeCompare(b)));
        return JSON.stringify(ids, null, 2) + "\n";
    }
    const a = parseRuntime(asText(existing)), b = parseRuntime(asText(incoming));
    const out = { ...a };
    for (const [id, l] of Object.entries(b)) out[id] = { name: l.name !== id ? l.name : (a[id]?.name ?? l.name), table: { ...(a[id]?.table ?? {}), ...l.table } };
    return `// GENERATED by OpenRock localization - do not edit.\n${RUNTIME_MODULE_PREFIX}${JSON.stringify(out)};\n`;
}

/** Appends pack.name / pack.description to every texts/*.lang that lacks them (the manifests reference these keys). */
function injectPackStrings(modManifest, maps) {
    const name = modManifest.displayName ?? modManifest.name;
    const description = modManifest.description ?? "";
    for (const map of maps) {
        if (!map) continue;
        for (const [rel, data] of [...map]) {
            if (!isLangFile(rel)) continue;
            const table = parseLang(asText(data));
            if (!table.has("pack.name")) table.set("pack.name", name);
            if (!table.has("pack.description")) table.set("pack.description", description);
            map.set(rel, Buffer.from(serializeLang(table, { header: HEADER }), "utf8"));
        }
    }
}

module.exports = { isMergedLangOutput, mergeLangOutput, injectPackStrings };
