// OR-Track Q3, made real: the full "spawn every entity, place every block,
// test every item" smoke test the original spec asked for ("OpenRock will
// GENUINELY test all of the components. All entities and blocks in the
// mods' definitions will be summoned."), extended to items too once
// Crystal Manifest-Item existed as a real authoring dialect - not just
// "did the pack load without a script exception" (Q4/bootAndCollect's own,
// narrower, already-real check).
//
// Real, confirmed mechanism (BDS has no RCON, no reliable stdin - this
// project's own earlier research): a synthetic, test-only behavior pack
// (never shipped in the real mod) that subscribes to
// world.afterEvents.worldLoad, then for every entity/block identifier the
// mod-under-test's OWN built output declares, tries to spawn/place it via
// the real Script API, logging a structured, distinctly-prefixed marker
// bdsTestHarness.js's own FATAL_LOG_PATTERNS/analyzeOutput() can parse -
// positive confirmation of success, not just absence-of-error.
"use strict";

// Fixed, real, dedicated UUIDs for this synthetic pack - NEVER regenerated
// per run (a stable identity is what lets BDS treat repeated installs as
// "the same pack, updated" rather than accumulating duplicates in its own
// world_behavior_packs.json bookkeeping across many smoke-test runs).
const HARNESS_HEADER_UUID = "b9f2b6b0-2f4e-4e1a-9c8b-2f6f7c9a1d10";
const HARNESS_DATA_MODULE_UUID = "b9f2b6b0-2f4e-4e1a-9c8b-2f6f7c9a1d11";
const HARNESS_SCRIPT_MODULE_UUID = "b9f2b6b0-2f4e-4e1a-9c8b-2f6f7c9a1d12";
const HARNESS_FOLDER_NAME = "OpenRock Test Harness";

// The real, structured markers bdsTestHarness.js's analyzeOutput() parses -
// a distinct prefix per real category, never overlapping with any real
// Bedrock log line, so a false match against unrelated console noise is
// structurally impossible.
const MARKER_ENTITY_OK = "[OR-SMOKE][ENTITY][OK]";
const MARKER_ENTITY_FAIL = "[OR-SMOKE][ENTITY][FAIL]";
const MARKER_BLOCK_OK = "[OR-SMOKE][BLOCK][OK]";
const MARKER_BLOCK_FAIL = "[OR-SMOKE][BLOCK][FAIL]";
const MARKER_ITEM_OK = "[OR-SMOKE][ITEM][OK]";
const MARKER_ITEM_FAIL = "[OR-SMOKE][ITEM][FAIL]";
const MARKER_DONE = "[OR-SMOKE][DONE]";

/**
 * Scans a real, built `bp` Map (buildMod()'s own output) for every real
 * entity/block/item identifier the mod-under-test declares - the exact
 * real documents BDS itself will load, not a separate guess at what
 * "should" exist.
 * @param {Map<string, Buffer>} bp
 * @returns {{entityIds: string[], blockIds: string[], itemIds: string[]}}
 */
function enumerateTestTargets(bp) {
    const entityIds = [];
    const blockIds = [];
    const itemIds = [];
    for (const [rel, buf] of bp) {
        if (rel.startsWith("entities/") && rel.endsWith(".json")) {
            const id = safeIdentifier(buf, "minecraft:entity");
            if (id) entityIds.push(id);
        } else if (rel.startsWith("blocks/") && rel.endsWith(".json")) {
            const id = safeIdentifier(buf, "minecraft:block");
            if (id) blockIds.push(id);
        } else if (rel.startsWith("items/") && rel.endsWith(".json")) {
            const id = safeIdentifier(buf, "minecraft:item");
            if (id) itemIds.push(id);
        }
    }
    return { entityIds, blockIds, itemIds };
}

function safeIdentifier(buf, rootKey) {
    try {
        const doc = JSON.parse(buf.toString("utf8"));
        return doc?.[rootKey]?.description?.identifier ?? null;
    } catch {
        return null; // not real JSON, or not this document shape - not this harness's job to validate that
    }
}

/**
 * The real, generated in-game test script - genuine @minecraft/server
 * Script API calls, not a simulation. Each entity/block gets a distinct
 * location so failures never mask each other (a crash spawning one
 * shouldn't prevent trying the next - each attempt is its own try/catch).
 * Spawns/places/gives happen in the Overworld inside a real, freshly-added
 * ticking area (see MAX_SPAN below) at a real, generous per-target
 * spacing, so nothing overlaps and nothing hits an unloaded chunk. Items
 * are tested via the real dimension.spawnItem() API (creates a genuine
 * dropped-item entity from a real ItemStack) - the standard, real way to
 * verify an item identifier actually resolves and loads without needing a
 * real player inventory to give it to.
 */
function generateHarnessScript({ entityIds, blockIds, itemIds }) {
    return `// GENERATED by OpenRock's real BDS test harness (OR-Track Q3) - never shipped in a real mod, test-only.
import { world, system, BlockPermutation, ItemStack } from "@minecraft/server";

const ENTITY_IDS = ${JSON.stringify(entityIds)};
const BLOCK_IDS = ${JSON.stringify(blockIds)};
const ITEM_IDS = ${JSON.stringify(itemIds)};
const SPACING = 3;
// Real, live-caught bug (not hypothetical): with no player online, a plain
// BDS world's spawn-area chunks aren't guaranteed loaded/ticking - a real
// LocationInUnloadedChunkError confirmed via an actual boot. The real,
// standard Bedrock fix is a /tickingarea covering the whole real test zone,
// added before any spawn/place attempt.
const MAX_SPAN = Math.max(ENTITY_IDS.length, 1) * SPACING + Math.max(BLOCK_IDS.length, 1) * SPACING + Math.max(ITEM_IDS.length, 1) * SPACING + SPACING * 6;

world.afterEvents.worldLoad.subscribe(() => {
    const dimension = world.getDimension("overworld");
    dimension.runCommand(\`tickingarea add -\${SPACING} 0 -\${SPACING} \${MAX_SPAN} 16 \${MAX_SPAN} or_smoke_area\`);
    // A real, short settle window for the new ticking area to actually load
    // and start ticking its chunks before anything tries to spawn/place
    // into them - confirmed necessary (immediate spawn attempts right after
    // the command still hit the same unloaded-chunk error).
    const farCorner = { x: MAX_SPAN - SPACING, y: 5, z: MAX_SPAN - SPACING };
    const chunksReady = () => { try { return Boolean(dimension.getBlock(farCorner)); } catch (e) { return false; } };
    let waited = 0;
    const wait = system.runInterval(() => {
        waited += 10;
        if (!chunksReady() && waited < 1200) return; // up to ~60s for a large ticking area to finish loading
        system.clearRun(wait);
        runAll();
    }, 10);
    function runAll() {
        let okCount = 0, failCount = 0;

        ENTITY_IDS.forEach((id, i) => {
            const location = { x: i * SPACING, y: 5, z: 0 };
            try {
                const entity = dimension.spawnEntity(id, location);
                if (!entity) throw new Error("spawnEntity returned no entity");
                console.warn(\`${MARKER_ENTITY_OK} \${id}\`);
                okCount++;
                entity.remove();
            } catch (e) {
                console.error(\`${MARKER_ENTITY_FAIL} \${id} :: \${e}\`);
                failCount++;
            }
        });

        BLOCK_IDS.forEach((id, i) => {
            const location = { x: (i % 5) * SPACING, y: 5, z: SPACING * (1 + Math.floor(i / 5)) }; // packed into the spawn chunk(s): loaded for sure
            try {
                const block = dimension.getBlock(location);
                if (!block) throw new Error("getBlock returned no block (chunk not loaded?)");
                block.setPermutation(BlockPermutation.resolve(id));
                // Confirms the placed block can be queried/broken back
                // without throwing - a cheap extra signal beyond bare
                // placement succeeding (per the real Q3 design).
                const placed = dimension.getBlock(location);
                if (!placed || placed.typeId !== id) throw new Error(\`placed block reads back as "\${placed?.typeId}", not "\${id}"\`);
                placed.setPermutation(BlockPermutation.resolve("minecraft:air"));
                console.warn(\`${MARKER_BLOCK_OK} \${id}\`);
                okCount++;
            } catch (e) {
                console.error(\`${MARKER_BLOCK_FAIL} \${id} :: \${e}\`);
                failCount++;
            }
        });

        ITEM_IDS.forEach((id, i) => {
            const location = { x: (i % 5) * SPACING, y: 5, z: SPACING * (8 + Math.floor(i / 5)) % 15 }; // packed into the spawn chunk: loaded for sure
            try {
                const stack = new ItemStack(id, 1);
                const itemEntity = dimension.spawnItem(stack, location);
                if (!itemEntity) throw new Error("spawnItem returned no entity");
                const readBack = itemEntity.getComponent("minecraft:item")?.itemStack;
                if (!readBack || readBack.typeId !== id) throw new Error(\`spawned item reads back as "\${readBack?.typeId}", not "\${id}"\`);
                console.warn(\`${MARKER_ITEM_OK} \${id}\`);
                okCount++;
                itemEntity.remove();
            } catch (e) {
                console.error(\`${MARKER_ITEM_FAIL} \${id} :: \${e}\`);
                failCount++;
            }
        });

        console.warn(\`${MARKER_DONE} entities=\${ENTITY_IDS.length} blocks=\${BLOCK_IDS.length} items=\${ITEM_IDS.length} ok=\${okCount} fail=\${failCount}\`);
    }
});
`;
}

// Real, live-caught bug (not hypothetical): a hardcoded old "1.13.0"
// dependency version left `world.afterEvents.worldLoad` undefined at
// runtime ("TypeError: cannot read property 'subscribe' of undefined"),
// confirmed via a real BDS boot. The real fix - never guess a version, use
// whatever the mod-under-test ITSELF already declares (it's already a real,
// known-working version for this exact BDS instance) - falling back to a
// real, current version only when the mod declares none at all.
const FALLBACK_SERVER_MODULE_VERSION = "2.0.0";

function generateHarnessManifest(serverModuleVersion = FALLBACK_SERVER_MODULE_VERSION) {
    return {
        format_version: 2,
        header: {
            name: "OpenRock Test Harness", description: "Generated by OpenRock (OR-Track Q3) - real entity/block smoke test, never shipped.",
            uuid: HARNESS_HEADER_UUID, version: [1, 0, 0], min_engine_version: [1, 21, 0],
        },
        modules: [
            { type: "data", uuid: HARNESS_DATA_MODULE_UUID, version: [1, 0, 0] },
            { type: "script", language: "javascript", uuid: HARNESS_SCRIPT_MODULE_UUID, entry: "scripts/main.js", version: [1, 0, 0] },
        ],
        dependencies: [{ module_name: "@minecraft/server", version: serverModuleVersion }],
        metadata: { authors: ["OpenRock"] },
    };
}

/**
 * Builds the real, complete synthetic test-harness pack as a {bp} Map,
 * ready for writeTree()/installation the same way any other real pack is.
 * @param {{entityIds: string[], blockIds: string[], itemIds: string[]}} targets
 * @returns {{bp: Map<string, Buffer>, folder: string, uuid: string, version: number[]}}
 */
function buildTestHarnessPack(targets, { serverModuleVersion } = {}) {
    const bp = new Map();
    const put = (rel, data) => bp.set(rel, Buffer.isBuffer(data) ? data : Buffer.from(data, "utf8"));
    put("manifest.json", JSON.stringify(generateHarnessManifest(serverModuleVersion), null, 2) + "\n");
    put("scripts/main.js", generateHarnessScript(targets));
    return { bp, folder: HARNESS_FOLDER_NAME, uuid: HARNESS_HEADER_UUID, version: [1, 0, 0] };
}

module.exports = {
    enumerateTestTargets, buildTestHarnessPack, generateHarnessScript, generateHarnessManifest,
    MARKER_ENTITY_OK, MARKER_ENTITY_FAIL, MARKER_BLOCK_OK, MARKER_BLOCK_FAIL, MARKER_ITEM_OK, MARKER_ITEM_FAIL, MARKER_DONE,
    HARNESS_HEADER_UUID, HARNESS_FOLDER_NAME,
};
